/**
 * Pre-build script for Firebase App Hosting.
 *
 * Firebase App Hosting injects config as FIREBASE_WEBAPP_CONFIG (a JSON blob),
 * but CRA only inlines env vars that start with REACT_APP_*.
 * This script bridges the gap by writing .env.production.local before the build.
 */
const fs = require('fs');
const path = require('path');

const webappConfig = process.env.FIREBASE_WEBAPP_CONFIG;

if (!webappConfig) {
  console.log('[firebase-env] No FIREBASE_WEBAPP_CONFIG found — skipping (local dev).');
  process.exit(0);
}

let config;
try {
  config = JSON.parse(webappConfig);
} catch (err) {
  console.error('[firebase-env] Failed to parse FIREBASE_WEBAPP_CONFIG:', err.message);
  process.exit(1);
}

const mapping = {
  apiKey: 'REACT_APP_FIREBASE_API_KEY',
  authDomain: 'REACT_APP_FIREBASE_AUTH_DOMAIN',
  projectId: 'REACT_APP_FIREBASE_PROJECT_ID',
  storageBucket: 'REACT_APP_FIREBASE_STORAGE_BUCKET',
  messagingSenderId: 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID',
  appId: 'REACT_APP_FIREBASE_APP_ID',
  measurementId: 'REACT_APP_FIREBASE_MEASUREMENT_ID',
};

const lines = ['# Auto-generated by scripts/firebase-env.js — do not edit'];

for (const [configKey, envKey] of Object.entries(mapping)) {
  if (config[configKey]) {
    lines.push(`${envKey}=${config[configKey]}`);
  }
}

const envPath = path.join(__dirname, '..', '.env.production.local');
fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf8');
console.log(`[firebase-env] Wrote ${lines.length - 1} vars to .env.production.local`);
